In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset/emails.csv", encoding="latin-1")

In [3]:
df = df[["v1", "v2"]]

df.columns = ["label", "message"]

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['label', 'message']

In [5]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [6]:
df.dropna(inplace=True)

df.isnull().sum()

label      0
message    0
dtype: int64

In [7]:
print("Before :",df.shape)

df.drop_duplicates(inplace=True)

print("After :",df.shape)

Before : (5572, 2)
After : (5169, 2)

In [8]:
df["label"] = df["label"].map({
    "ham":0,
    "spam":1
})

df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [9]:
df["message"] = df["message"].str.lower()

df.head()

   label                                            message
0      0  go until jurong point, crazy.. available only ...
1      0                      ok lar... joking wif u oni...
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0  u dun say so early hor... u c already then say...
4      0  nah i don't think he goes to usf, he lives aro...

In [10]:
X = df["message"]

y = df["label"]

In [11]:
print("Features :",X.shape)

print("Target :",y.shape)

Features : (5169,)
Target : (5169,)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(X)

In [13]:
print(X.shape)

(5169, 8672)

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [15]:
print("Training :",X_train.shape)

print("Testing :",X_test.shape)

Training : (4135, 8672)
Testing : (1034, 8672)

In [16]:
import joblib
import os

os.makedirs("../models",exist_ok=True)

joblib.dump(cv,"../models/vectorizer.pkl")

print("Vectorizer Saved Successfully")

Vectorizer Saved Successfully

In [17]:
joblib.dump(X_train,"../outputs/X_train.pkl")
joblib.dump(X_test,"../outputs/X_test.pkl")
joblib.dump(y_train,"../outputs/y_train.pkl")
joblib.dump(y_test,"../outputs/y_test.pkl")

print("Processed Data Saved Successfully")

Processed Data Saved Successfully

In [18]:
print("="*50)

print("PHASE 2 COMPLETED")

print("="*50)

print("Rows :",df.shape[0])

print("Columns :",df.shape[1])

print("Training Samples :",X_train.shape[0])

print("Testing Samples :",X_test.shape[0])

print("="*50)

==================================================
PHASE 2 COMPLETED
==================================================
Rows : 5169
Columns : 2
Training Samples : 4135
Testing Samples : 1034
==================================================